server:
  port: 8088

spring:
  application:
    name: gateway-server
  jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  redis:
    host: 172.31.185.112
    port: 6379
    password: minDwPnaEzMyF
    #topic:  __keyevent@0__:expired
    database: 1

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registry-fetch-interval-seconds: 10

zuul:
  prefix: /api
  routes:
    upms-service:
      path: /upms-service/**
    user-service:
      path: /user-service/**
    group-service:
      path: /group-service/**
    message-service:
      path: /message-service/**
    ticket-service:
      path: /ticket-service/**
    wechat-service:
      path: /wechat-service/**
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin

swagger:
  butler:
    auto-generate-from-zuul-routes: true
    #generate-routes: wechat-service
    #ignore-routes: config-server
    api-docs-path: v2/api-docs
    swagger-version: 2.0

## 忽略配置
ignore:
  urls:
  - /swagger-resources/**
  - /swagger-ui.html
  - /api/**
  - /**/v2/api-docs
  - /webjars/**
  - /bus/**
  - /actuator/**
  - /wechat/accessToken
  - /staff/login