server:
  port: 8001

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://192.168.2.100:8000/eureka/
    registry-fetch-interval-seconds: 10

spring:
  application:
    name: upms-service
  devtools:
    restart:
      enabled: false
  jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null


  datasource:
    url: jdbc:mysql://192.168.2.100:3306/leta_upms
    username: root
    password: leta123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


## 忽略配置
ignore:
  urls:
    - /swagger-resources/**
    - /swagger-ui.html
    - /v2/api-docs
    - /webjars/**
    - /upms-service/**
    - /config-server/**
    - /bus/**
    - /actuator/**

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: cn.leta.upms.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true


swagger:
  title: 权限系统接口文档
  description:
  base-package: cn.leta.upms